name: Docs

on:
  push:
    branches: [master]

jobs:
  release:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        run: |
          rustup show
          rustup component add rust-docs
      - name: Setup protoc
        uses: arduino/setup-protoc@v1

      - name: Build website
        run: |
          cd docs
          yarn install
          yarn run build

      - name: Build rustdocs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps

      - name: Copy rustdocs
        run: |
          cp -r ./target/doc docs/.vuepress/dist/rustdocs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./docs/.vuepress/dist
          keep_files: true
